function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(10)=1;
    ys_(20)=1;
    params(28)=params(11)/((1-params(17))*params(12));
    params(23)=1000*params(22)*params(35)/(params(28)*(1-params(27))^141*(1-params(24))^141);
    params(18)=params(28)*params(23)/1000/params(22)*params(15);
    d0=exp((-params(21))*params(1));
    params(16)=(d0^(1+params(7))/params(10))^(1/(params(7)+params(8)));
    params(20)=d0*params(16);
    params(19)=params(20);
    params(5)=params(12)/(params(20)*params(13));
    ys_(4)=0;
    ys_(5)=0;
    ys_(6)=0;
    ys_(15)=params(14)+params(34)*exo_(2);
    ys_(2)=params(3);
    ys_(3)=0;
    [ys_(1),ys_(7)]=get_Z(params(5),params(26),params(4),params(13),params(3),params(6),params(27),params(28),params(29),params(24),params(14),params(22),params(23),params(10),params(7),params(2),params(1),params(21),params(34),params(8));
    ys_(14)=exp((-params(21))*ys_(7));
    ys_(13)=(params(14)+params(34)*exo_(2))^(1/(params(22)-1));
    ys_(12)=(ys_(14)^(1-params(7))/params(10))^(1/(params(7)+params(8)));
    ys_(8)=ys_(14)*ys_(12);
    ys_(9)=ys_(8);
    ys_(11)=ys_(14);
    ys_(10)=1/params(9);
    ys_(17)=ys_(7)*params(37);
    ys_(18)=1000*ys_(5)*ys_(15)/(ys_(4)+1e-8);
    ys_(19)=ys_(2)*ys_(1)^(1-params(7))*(1/(1-params(7))*ys_(9)^(1-params(7))-params(10)/(1+params(8))*ys_(12)^(1+params(8)))/(1-params(9));
    % Auxiliary equations
end
